## Numpy array

In [14]:
import numpy as np

In [15]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a2 = a[np.newaxis, :]
a2
a2.shape

(1, 10)

In [17]:
b=a[:, np.newaxis]
b
b.shape

(10, 1)

In [18]:
a = np.array([1, 2, 3, 4, 5, 6])
a.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a2.shape

(3, 4)

In [21]:
print(a2[2,3])

12


In [22]:
np.array([1, 2, 3])

array([1, 2, 3])

In [23]:
np.array([2, 1, 5, 3, 7, 4, 6, 8])

array([2, 1, 5, 3, 7, 4, 6, 8])

In [24]:
np.sort(np.array([2, 1, 5, 3, 7, 4, 6, 8]))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [26]:
# concatenate
z=np.concatenate((x, y), axis=0)
z.shape

(3, 2)

In [27]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.shape

(3, 2, 4)

In [28]:
array_example.ndim

3

In [29]:
array_example.size

24

In [30]:
array_example.shape

(3, 2, 4)

In [32]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [34]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [35]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [37]:
col_vector = a[:, np.newaxis]
col_vector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])