## Numpy Indexing and slicing

In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])


In [2]:
a[0]

1

In [3]:
a[-2]

6

In [4]:
b=np.arange(0,12,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [7]:
print(b)

[ 0  2  4  6  8 10]


In [8]:
print(b[0,1])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [27]:
c=b.reshape(3,2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [28]:
c[0]

array([0, 2])

In [30]:
d=[(c<5)|(c>8)]
d

[array([[ True,  True],
        [ True, False],
        [False,  True]])]